### ISSUE TITLE
1 Nov

### ISSUE THREAD

**Issue by ahill6** [ahill6/Research#2]
DOING: Current calculation of relative performance may bias results against situations where a few predictors are significantly better than all others.  Need to modify calculation to remove this bias.

DONE: Repaired summary methods, implemented additional automation to stats/abcd, initial analysis of data.

TODO: Make overall average Scott-Knott report and follow-on analysis of collected data.  Publish remaining datasets to Github (apparently only published for accumulo).

ROADBLOCKS: N/A

ADMIN: N/A

REPORT

Results of stats.py for all measures on all datasets are available [here][results].  Due to a printing oversight, each value shows as 100x bigger (e.g. 94% shows as 9400).  As a first quick analysis, [this][summary] document has a summary.  The summary was generated by considering the top-ranked Scott-Knott groups, and determining the distribution of each variable in those "best" groups.

[Spill levels][spillchart] show a clear trend of improved performance (or rather, higher inclusion in highest Scott-Knott groups) that is directly related to spill level.  

The results for [tree depth][depthchart] show no meaningful pattern, and all depths are relatively uniform in their representation in best Scott-Knott groups, potentially suggesting that tree depth is not an important factor in performance.

[This][methodchart] shows that the four best-known and most widely used methods among the bunch (KD, 2-Means, Random Projection, PCA) perform significantly better than all other methods, which confirms expected behavior.

THREATS TO VALIDITY

As mentioned in the TODO portion, the current method of aggregating data is simply to find the percentage of Scott-Knott best groups that fall into each category.  This may unfairly bias the results against, e.g. against spill=0.15 or rp. Both of these did better than others in accumulo recall, which had only 6 results in the top Scott-Knott group.  That represents ~1% of the whole for pd as done, rather than something closer to 10% since they performed best on 1 of 10 datasets.

[results]: https://github.com/ahill6/Research/tree/master/data/classifier
[summary]: https://github.com/ahill6/Research/blob/master/reports/Charts%20and%20Graphs.ods
[depthchart]: https://docs.google.com/spreadsheets/d/1GAzdCMeEKVHurhA0e59QC28GudO92WjCsogpiyGSdnI/pubchart?oid=1762328893&format=interactive
[spillchart]: https://docs.google.com/spreadsheets/d/1GAzdCMeEKVHurhA0e59QC28GudO92WjCsogpiyGSdnI/pubchart?oid=176811727&format=interactive
[methodchart]: https://docs.google.com/spreadsheets/d/1GAzdCMeEKVHurhA0e59QC28GudO92WjCsogpiyGSdnI/pubchart?oid=636588721&format=interactive

**Comment by timm** [comment]
u use open office for graphs? normally i doubt the spreadsheet stuff since excel has such low-res graphics. but the following look good. in generaly do you recommend open office?

![image](https://cloud.githubusercontent.com/assets/29195/19940020/a52866dc-a101-11e6-9b1b-ad8f0f0c468a.png)

in these, what is "best"? top ranked produced by scottKnott+a12?  assuming "yes" then...

is spill top-left? then that suggests that more spill is clearly better. 
- any downside? runtimes?
- when u reported "best" pf, you meant "lowest", right?

the tree-depth stuff is cool. 
- is root depth=1? 
- so depth=5 means 16 clusters?

the top-right results says:
- i should dump where for something else (but not spectral). right?
-  any comments on 2-means vs kd vs pc vs rp? is one faster than the other? simpler? e.g. pcs assumes all attributes MUST be numeric.  as does class kd trees.  but i can mess with distance metrics to handle non-numerics with rp and 2-means

**Comment by timm** [comment]
hang on 

![image](https://cloud.githubusercontent.com/assets/29195/19940452/19f37bae-a103-11e6-93b0-353fd9005504.png)

are these your raw pd,pf numbers? they look... odd. some over 100, some very low

what are your pdf, pdf numbers?

please show me **my** preferred report format (all those damn quartiles). but feel free to delete the tree depth stuff since that seems to have zero effect

**Comment by ahill6** [comment]
Will do for getting you quartiles.

I like Open Office in general, although there are a few issues (e.g. if someone sends me a document with equations made with Equation Editor, they don't appear).  Haven't been able to figure out if that is a certain version of Office/Equation Editor causing that.
The graphs here were actually made with Google Sheets because I couldn't get the .ods's to open on my chromebook when writing the report.  I like how they turned out, but Open Office is infinitely easier to use.

Yes, "best" is top-ranked by SK+A12, the data that looks odd is the total number of times each was in the top group (that's why the raw data has numbers over 100 NOT raw pf/pd/et al., e.g. 2-means pd had 116 appearances in the top SK+A12 group out of the 530 total items in the top groups), where top groups is plural because there was one top group for each dataset.

Best pf **does** mean lowest

top-right says that Where is not the best way to find nearest neighbors quickly.  I would say overall for this data PCA is best; although when I was playing with non-defect prediction datasets, KD was more consistent over many types of data.  2-means is an order of magnitude slower than all the others, and RP makes the top group...but just barely.  PCA and KD seem far and away better than 2-means and RP, with KD being the faster and (without more than anecdote to back it up) more broadly effective.

**Comment by timm** [comment]
all this and we end up with kd-trees hahahaahahahha

what data sets?

i any case, there is a paper here, if you want. FIRST we look at the raw pd,pf nums looking for any stinkers. then you spend a tedious week or two reading about how clustering is used in se. 

how does kd handle discrete values?
